### ISSUE TITLE
after migration to svelte 4: "cannot find module /.../node_modules/svelte/compiler"

### ISSUE THREAD

**Issue by m1027** [coc-extensions/coc-svelte#65]
Hi,

when migrating from svelte 3 to 4, coc-svelte complains in every file's top line with this message:

  > ⚠ <script lang="ts">
  >       Cannot find module '/home/user/src/my_project/node_modules/svelte/compiler'
  >       Require stack:
  >       - /home/user/.config/coc/extensions/node_modules/coc-svelte/node_modules/
  >       svelte-language-server/dist/src/importPackage.js
  >       - /home/user/.config/coc/extensions/node_modules/coc-svelte/node_modules/
  >       svelte-language-server/dist/src/lib/documents/configLoader.js
  >       - /home/user/.config/coc/extensions/node_modules/coc-svelte/node_modules/
  >       svelte-language-server/dist/src/lib/documents/Document.js
  >       - /home/user/.config/coc/extensions/node_modules/coc-svelte/node_modules/
  >       svelte-language-server/dist/src/lib/documents/index.js
  >       - /home/user/.config/coc/extensions/node_modules/coc-svelte/node_modules/
  >       svelte-language-server/dist/src/server.js
  >       - /home/user/.config/coc/extensions/node_modules/coc-svelte/node_modules/
  >       svelte-language-server/bin/server.js (svelte)

When going back to svelte 3, the issue is gone.

Any pointers?

**Comment by e6a5** [comment]
I am currently facing the same problem. Is there any help?

**Comment by dummdidumm** [comment]
`coc-svelte` is a bit out of date right now, if it releases a new version with the most recent version of the `svelte-language-server` it should work again

**Comment by m1027** [comment]
The issue seems to be gone.

Meanwhile there has been an update of coc-clangd to version 0.29.0.

I leave this open for a while for others to test and confirm.

**Comment by m1027** [comment]
Please ignore my previous all-clear signal.

I am sorry, my test was invalid and the issue persists.

**Comment by KyrillGobber** [comment]
I installed the extension via packer and updated the package.json to use the latest "svelte-language-server": "^0.15.13".
Looks like i works now.
If you don't know how to do it:
- 'use {'coc-extensions/coc-svelte'}' in your plugins.lua or wherever you have your packer config
- open the coc-svelte folder (default for packer is ~/.local/share/nvim/site/pack/packer/start/coc-svelte)
- open the package.json and update the svelte-language-server to 0.15.13 (which is the latest version right now)
- Probably optional, but I did it: update typescript and typescript-svelte-plugin as well.
- yarn
- yarn build

open nvim and :PackerSync (or maybe :PackerCompile is enough, I don't know)
I restarted nvim and it works as it should now.

I see there are PRs from last year, still open, that do a similar thing. So I guess this is the best way for now.

**Comment by m1027** [comment]
@KyrillGobber : Thanks for sharing the details and a working solution when using `packer`.

I am on `Plug` here. I can also edit `package.json` of `coc-svelte` as you explained, however, currently I fail to update the node packages accordingly. Probably this is because I install from nvim via `:CocInstall coc-svelte` and not separately? I need to investigate that further which is admittedly a bit OT.

**Comment by KyrillGobber** [comment]
@m1027 Uninstall the svelte plugin from coc: ':CocUninstall coc-svelte' then install it as normal plugin with plug. After you run yarn and yarn build in the coc-svelte plugin folder, PlugInstall again and it should be ready to go.

You can check if it's listed in  'CocList extensions'

Yes it's a bit OT, but the PRs aren't getting merged anyway, and people gotta get help somewhere right

**Comment by m1027** [comment]
@KyrillGobber: That worked! Fantastic!

For others following this, here a summary how to make coc-svelte work after migration to svelte 4:

- You need to update `coc-svelte`'s `package.json` manually as this is currently lacking upstream. Changes I made: `"svelte-language-server": "^0.15.3"`, `"typescript": "^5.1.6"`, `"typescript-svelte-plugin": "^0.3.28"`
- To update the node packages, you `cd` into your `coc-svelte` directory and do `yarn` and `yarn build`; locate your config folder via `:CocList extensoins`
- Note: In case you installed `coc-svelte` via `:CocInstall coc-svelte`, undo that first: `:CocUninstall coc-svelte` and install `coc-svelte` either via `Packer` or as a separate plugin via `Plug`
- In case of `Plug` I edited `init.vim` with this line: `Plug 'coc-extensions/coc-svelte', {'branch': 'master', 'do': 'yarn install --frozen-lockfile'}` and then did `PlugUpdate` as usual; again use `CocList extensions` to verify

**Comment by KyrillGobber** [comment]
@m1027 Excellent. I'll try to open a PR later, maybe it'll get merged.

**Comment by m1027** [comment]
I continue here as it is unclear yet whether this is related to this issue or not:

`coc-svelte` against svelte 4 does not behave as usual in at least these too issues now:
- Syntax errors anywhere in a `*.svelte` file get detected but are indicated by a error message in line 1 of the file
- Jumping to definition does not work (definition not found) while the same works for `C` code

@KyrillGobber: Does jump to definition still work in `*.svelte` files in your case?

**Comment by m1027** [comment]
After some further tests show:

Generally, all LSP features seem to work when testing against fresh simple sveltekit projects. So the fixes for `coc-svelte` mentioned above seem to hold.

The bad news: I have migrated some larger sveltekit projects and here LSP features may stop working in `+page.svelte`. As far as I could track that down: A`+page.server.ts` file laying side-by-side can trigger that behaviour - without indicating though what part of the code is responsible for that.

**Comment by m1027** [comment]
I reopen this issue: I haven't found a working way to make `coc-svelte` work against `svelte-4` yet.

Summary:

While https://github.com/coc-extensions/coc-svelte/issues/65#issuecomment-1623773751 tries to update `coc-svelte`'s deps and indeed avoids the original issue of this topic, it renders `coc-svelte` unusable and other areas. Most notably: `coc-svelte` may simply refuse to work at all even without migrating to svelte 4.

How to reproduce the issues:

After updating the dependencies of `coc-svelte`manually as shown above, play with larger projects incl. `+page.server.ts`, `.env` etc. At some point `coc-svelte` just stops showing syntax hints and doesn't find definitions anymore.

After uninstalling the self-made `coc-svelte` and reverting to `:CocInstall coc-svelte` again the follow-up issues are gone (but obivously, I need to revert to svelte-3 then too).

**Comment by m1027** [comment]
To not further block the migration to svelte 4 here due to this open issue:

With neovim's native lsp + mason + mason-lspconfig instead of coc, I have a comparable solution now that works with svelte 4, too.

**Comment by KyrillGobber** [comment]
@m1027 We had the same idea: Yesterday I switched to lsp with mason and it seems to work just fine. Looks like native lsp is the way to go indeed.

**Comment by hexh250786313** [comment]
Actually, builtin-lsp isn't doing anything out of the ordinary. It's simply firing up the svelte lsp server in a standard way.

https://github.com/neovim/nvim-lspconfig/blob/6e5c78ebc9936ca74add66bda22c566f951b6ee5/lua/lspconfig/server_configurations/svelte.lua#L1

Similarly, coc has the capability to kickstart the svelte lsp server to accomplish the same tasks.

```json
// coc-settings.json
  "languageserver": {
    "svelte": {
      "enable": true,
      "command": "svelteserver",
      "args": ["--stdio"],
      "rootPatterns": ["package.json", ".git", ".editorconfig"],
      "filetypes": ["svelte"]
    },
  }
```

![image](https://github.com/coc-extensions/coc-svelte/assets/26080416/7044f2db-5763-40f2-bd2e-1e4ca52d5918)

If you're encountering any hiccups with coc-svelte, this could be a worthwhile alternative to explore.

**Comment by m1027** [comment]
Thanks for the update.

I am not using coc anymore and thus cannot judge whether this issue is resolved.

But the latest comment sounds like there is a solution. So I am closing this issue.
